services:
  traefik:
    extends: 
      file: /home/calebh/infrastructure/containers/traefik.yml
      service: traefik
    profiles:
      - proxy
      - proxy-debug
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/cf-dns-api-token
    secrets:
      - cf-dns-api-token
    labels:
      traefik.http.routers.traefik-secure.tls.domain[0].sans: "*.apps.husovich.com"
      traefik.http.routers.traefik.rule: Host(`traefik.apps.husovich.com`)
      traefik.http.routers.traefik-secure.rule: Host(`traefik.apps.husovich.com`)

  whoami:
    extends:
      file: /home/calebh/infrastructure/containers/traefik.yml
      service: whoami
    profiles:
      - proxy-debug
    labels:
      traefik.http.routers.whoami-web.rule: Host(`whoami.apps.husovich.com`)
      traefik.http.routers.whoami-websecure.rule: Host(`whoami.apps.husovich.com`)

secrets:
  cf-dns-api-token:
    file: /home/calebh/secrets/CF_DNS_API_TOKEN

networks:
  traefik:
    external: true