services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    restart: unless-stopped
    cap_add:
      - SYS_RAWIO
    # ports:
    #   - "8080:8080" # webapp
    #   - "8086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - /home/calebh/app-data/scrutiny/config:/opt/scrutiny/config
      - /home/calebh/app-data/scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      # - "/dev/nvme0"
    networks:
      traefik:
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      # redirect https
      - traefik.http.middlewares.redirect-https.redirectScheme.scheme=https
      - traefik.http.middlewares.redirect-https.redirectScheme.permanent=true
      # HTTPS
      - traefik.http.routers.scrutiny-https.rule=Host(`scrutiny.apps.husovich.com`)
      - traefik.http.routers.scrutiny-https.entrypoints=https
      - traefik.http.routers.scrutiny-https.tls=true
      - traefik.http.routers.scrutiny-https.service=scrutiny
      # HTTP
      - traefik.http.routers.scrutiny-http.rule=Host(`scrutiny.apps.husovich.com`)
      - traefik.http.routers.scrutiny-http.entrypoints=http
      - traefik.http.routers.scrutiny-http.middlewares=redirect-https
      - traefik.http.routers.scrutiny-http.service=scrutiny
      # Port
      - traefik.http.services.scrutiny.loadbalancer.server.port=8080

networks:
  traefik:
    external: true