services:
  gateway:
    build:
      context: gw-build
      args:
        IGNITION_VERSION: 8.1.48
    image: localhost:5000/ignition:8.1.48-maker
    ports:
      - 9088:8088
      - 9043:8043
      - 1883:1883
    volumes:
      - ./gw-data:/usr/local/bin/ignition/data
    secrets:
      - gateway-activation-token
      - gateway-admin-password
    environment:
      DISABLE_QUICKSTART: true
      ACCEPT_IGNITION_EULA: "Y"
      IGNITION_EDITION: maker
      IGNITION_ACTIVATION_TOKEN_FILE: /run/secrets/gateway-activation-token
      IGNITION_LICENSE_KEY: 6QQ5-HE17
      GATEWAY_ADMIN_PASSWORD_FILE: /run/secrets/gateway-admin-password
    command:
      -n home-automation

secrets:
  gateway-activation-token:
    file: ./secrets/GATEWAY_ACTIVATION_TOKEN
  gateway-admin-password:
    file: ./secrets/GATEWAY_ADMIN_PASSWORD

volumes:
  gw-data: