services:
   actual-budget:
     image: docker.io/actualbudget/actual-server:latest
     container_name: actual-budget
     restart: unless-stopped
     volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - /home/calebh/app-data/actual:/data
     networks:
       traefik:
     labels:
       traefik.enable: true
       # HTTP
       traefik.http.routers.actual-budget.entrypoints: http
       traefik.http.routers.actual-budget.rule: Host(`budget.apps.husovich.com`)
       traefik.http.routers.actual-budget.middlewares: traefik-https-redirect
       traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme: https
       # HTTPS
       traefik.http.routers.actual-budget-secure.entrypoints: https
       traefik.http.routers.actual-budget-secure.rule: Host(`budget.apps.husovich.com`)
       traefik.http.routers.actual-budget-secure.tls.certresolver: myresolver

networks:
  traefik:
    external: true  