services:
   homebox:
     image: ghcr.io/hay-kot/homebox:latest  
     container_name: homebox
     restart: unless-stopped
     environment:
       HBOX_LOG_LEVEL: info
       HBOX_LOG_FORMAT: text
       HBOX_WEB_MAX_UPLOAD_SIZE: 10
     volumes:
      - ./hb-data:/data/
     networks:
       traefik:
     labels:
       traefik.enable: true
       # HTTP
       traefik.http.routers.homebox.entrypoints: http
       traefik.http.routers.homebox.rule: Host(`homebox.husovich.com`)
       traefik.http.routers.homebox.middlewares: traefik-https-redirect
       traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme: https
       # HTTPS
       traefik.http.routers.homebox-secure.entrypoints: https
       traefik.http.routers.homebox-secure.rule: Host(`homebox.husovich.com`)
       traefik.http.routers.homebox-secure.tls.certresolver: myresolver"

networks:
  traefik:
    external: true  